Repository sequentech/election-orchestra, pull requests merged in 2024-04, with the labels that each got.

#90 ✨ weighted voting support
  tally_election/performer_jobs.py
Labels: enhancement

#94 ✨ weighted voting support (#90)
  tally_election/performer_jobs.py
Labels: enhancement

#91 ✨ Check if the authorities are online
  public_api.py
Labels: enhancement

#95 ✨ Check if the authorities are online (#91)
  public_api.py
Labels: enhancement

#96 🐞 Trustees struggle to respond to director (#93)
  create_election/director_jobs.py
  tally_election/director_jobs.py
Labels: bug

#98 Bump cryptography from 42.0.2 to 42.0.4 (#97)
  requirements.txt
  setup.py
Labels: dependencies
